name: Devnet Build and Deploy

on:
  workflow_dispatch:
    inputs:
      priority_fee:
        description: 'Priority fee for transactions'
        required: true
        default: '30000'
        type: string

jobs:
  build:
    uses: solana-foundation/github-workflows/.github/workflows/reusable-build.yaml@1a62a52041b4a9beed9e96843062be1859447f1d
    with:
      program: 'async_vault_v2'
      program-id: '3Y4rpSYqrW9JRuiS3YosEXSSYHai4sFH3XMzAQmkNzFg'
      network: 'devnet'
      deploy: true
      upload_idl: true
      verify: false
      use-squads: false
      priority-fee: ${{ github.event.inputs.priority_fee }}
    secrets:
      DEVNET_SOLANA_DEPLOY_URL: ${{ secrets.DEVNET_SOLANA_DEPLOY_URL }}
      DEVNET_DEPLOYER_KEYPAIR: ${{ secrets.DEVNET_DEPLOYER_KEYPAIR }}
      PROGRAM_ADDRESS_KEYPAIR: ${{ secrets.PROGRAM_ADDRESS_KEYPAIR }}
