name: Test

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          install-solana: 'false'
          install-just: 'false'
          install-pnpm: 'false'
          rust-cache-key: 'unit-tests'
      - run: cargo test -p async_vault_v2 -p vault_common

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          install-anchor: 'true'
          install-nightly-rustfmt: 'true'
          rust-cache-key: 'integration-tests'
      - name: Build IDL and clients
        run: |
          pnpm run generate-idl
          pnpm run generate-clients
      - name: Run integration tests
        run: cargo test -p integration-tests
